DROP DATABASE IF EXISTS tb_final;
CREATE DATABASE tb_final;
USE tb_final;

CREATE TABLE ESTABELECIMENTO_CNES (
	codEstabelecimento INTEGER PRIMARY KEY,
    nomeEstabelecimento VARCHAR(200) NOT NULL
);

CREATE TABLE GRUPO (
	codGrupo INTEGER PRIMARY KEY,
    nomeGrupo VARCHAR(200) NOT NULL
);

CREATE TABLE SUBGRUPO (
	codSubgrupo INTEGER PRIMARY KEY,
    nomeSubgrupo VARCHAR(200) NOT NULL,
    codGrupo INTEGER,
    CONSTRAINT SUBGRUPO_GRUPO_FK FOREIGN KEY(codGrupo) REFERENCES GRUPO(codGrupo)
);

CREATE TABLE PROCEDIMENTO (
	codProcedimento INTEGER PRIMARY KEY,
    nomeProcedimento VARCHAR(200) NOT NULL
);

CREATE TABLE CARATER_ATENDIMENTO (
	codCarater INTEGER PRIMARY KEY,
    nomeCaraterAtendimento VARCHAR(200) NOT NULL
);

CREATE TABLE ATENDIMENTO (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	anoMes VARCHAR(6) NOT NULL,
	quantidade INTEGER NOT NULL,
    codEstabelecimento INTEGER,
    codGrupo INTEGER,
    codProcedimento INTEGER,
    codCarater INTEGER,
    CONSTRAINT ATENDIMENTO_ESTABELECIMENTO_FK FOREIGN KEY (codEstabelecimento)
		REFERENCES ESTABELECIMENTO_CNES(codEstabelecimento),
    CONSTRAINT ATENDIMENTO_GRUPO_FK FOREIGN KEY (codGrupo) 
		REFERENCES GRUPO(codGrupo),
	CONSTRAINT ATENDIMENTO_PROCEDIMENTO_FK FOREIGN KEY (codProcedimento) 
		REFERENCES PROCEDIMENTO(codProcedimento),
	CONSTRAINT ATENDIMENTO_CARATER_FK FOREIGN KEY (codCarater) 
		REFERENCES CARATER_ATENDIMENTO(codCarater)
) Engine=InnoDB;